# Generated by Django 6.1 on 2026-09-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=10)),
                ('weight', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=50)),
                ('feedback', models.TextField()),
                ('Dob', models.DateField(auto_now=True)),
                ('dobwithtime', models.DateTimeField(auto_now=True)),
                ('birthtime', models.TimeField(auto_now=True)),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
