# Generated by Django 6.1 on 2026-09-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleTable',
        ),
    ]
