# Generated by Django 6.1 on 2026-09-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ranksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('social_science', models.IntegerField()),
                ('total', models.IntegerField()),
                ('average', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
