# Generated by Django 6.1 on 2026-09-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_ranksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranksheet',
            name='average',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ranksheet',
            name='rank',
            field=models.BooleanField(),
        ),
    ]
