# Generated by Django 6.1 on 2026-09-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_alter_ranksheet_average_alter_ranksheet_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
    ]
