# Generated by Django 6.1.1 on 2026-09-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joined_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
