# Generated by Django 6.1.1 on 2026-10-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_student_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='orm.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=0),
        ),
    ]
