# Generated by Django 6.1.1 on 2026-10-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_remove_book_description_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
